//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdyDuck.DotIgnore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdyDuck.DotIgnore.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore file not found..
        /// </summary>
        internal static string ExcludeList_FromFile_FileNotFound {
            get {
                return ResourceManager.GetString("ExcludeList_FromFile_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path may not be null, empty or white-space-only..
        /// </summary>
        internal static string ExcludeList_FromFile_PathEmpty {
            get {
                return ResourceManager.GetString("ExcludeList_FromFile_PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read from stream..
        /// </summary>
        internal static string ExcludeList_FromStream_NotReadable {
            get {
                return ResourceManager.GetString("ExcludeList_FromStream_NotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern may not be null, empty or white-space-only..
        /// </summary>
        internal static string ExcludePattern_ctor_PatternEmpty {
            get {
                return ResourceManager.GetString("ExcludePattern_ctor_PatternEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern is a comment, starting with &apos;#&apos;..
        /// </summary>
        internal static string ExcludePattern_ExaminePattern_Comment {
            get {
                return ResourceManager.GetString("ExcludePattern_ExaminePattern_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name may not be null, empty or white-space-only..
        /// </summary>
        internal static string GitEnvironment_GetEnvironmentVariables_NameEmpty {
            get {
                return ResourceManager.GetString("GitEnvironment_GetEnvironmentVariables_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository path may not be null, empty or white-space-only..
        /// </summary>
        internal static string GitRepository_ctor_PathEmpty {
            get {
                return ResourceManager.GetString("GitRepository_ctor_PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path may not be empty..
        /// </summary>
        internal static string Matcher_Load_PathEmpty {
            get {
                return ResourceManager.GetString("Matcher_Load_PathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String may not be empty..
        /// </summary>
        internal static string Matcher_Load_StringEmpty {
            get {
                return ResourceManager.GetString("Matcher_Load_StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot merge Matchers with different string comparison types..
        /// </summary>
        internal static string Matcher_Merge_InvalidComparison {
            get {
                return ResourceManager.GetString("Matcher_Merge_InvalidComparison", resourceCulture);
            }
        }
    }
}
