//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdyDuck.DotIgnore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdyDuck.DotIgnore.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory does not exist..
        /// </summary>
        internal static string Global_DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("Global_DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist..
        /// </summary>
        internal static string Global_FileDoesNotExist {
            get {
                return ResourceManager.GetString("Global_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File system object is not a file..
        /// </summary>
        internal static string Global_NotAFile {
            get {
                return ResourceManager.GetString("Global_NotAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length may not be negative..
        /// </summary>
        internal static string MemoryFileSystemObject_ctor_LengthNegative {
            get {
                return ResourceManager.GetString("MemoryFileSystemObject_ctor_LengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root path length may not be negative..
        /// </summary>
        internal static string PhysicalDirectoryContents_ctor_RootLengthNegative {
            get {
                return ResourceManager.GetString("PhysicalDirectoryContents_ctor_RootLengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type of FileSystemInfo..
        /// </summary>
        internal static string PhysicalDirectoryContents_EnsureInitialized_InvalidType {
            get {
                return ResourceManager.GetString("PhysicalDirectoryContents_EnsureInitialized_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path must be absolute..
        /// </summary>
        internal static string PhysicalFileSystemProvider_ctor_PathNotAbsolute {
            get {
                return ResourceManager.GetString("PhysicalFileSystemProvider_ctor_PathNotAbsolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string PhysicalFileSystemProvider_ctor_PathNotFound {
            get {
                return ResourceManager.GetString("PhysicalFileSystemProvider_ctor_PathNotFound", resourceCulture);
            }
        }
    }
}
